import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { gameReducer } from '../../src/domain/reducer/index.js';
import { translateDiffToEvents } from '../../src/domain/diff-translator.js';
import { COMPARABLE_KEYS } from '../../src/domain/event-verifier.js';

/**
 * Simulate a state transition as the old handler would do it.
 * Returns the domain events generated by the diff-translator.
 */
function simulateTransition(handlerKey, before, mutate) {
  const after = structuredClone(before);
  mutate(after);
  // Compute a simple diff
  const set = {};
  const deleted = [];
  for (const key of new Set([...Object.keys(before), ...Object.keys(after)])) {
    if (JSON.stringify(before[key]) !== JSON.stringify(after[key])) {
      if (after[key] === undefined) {
        deleted.push(key);
      } else {
        set[key] = after[key];
      }
    }
  }
  const diff = { set, deleted };
  const events = translateDiffToEvents(handlerKey, diff, {
    gameId: 'test-game', playerId: 'user1', before, after,
  });
  return { after, events };
}

describe('Replay Accuracy', () => {
  it('full game lifecycle: state transitions produce replayable events', () => {
    let actualState = {};
    let allEvents = [];

    // 1. Game creation (not from diff - manual event)
    const gameCreatedEvent = {
      type: 'GameCreated', gameId: 'test-game', seq: 1,
      playerId: 'user1', payload: { player1Id: 'alice', player2Id: 'bob', generalId: 'test-game' },
    };
    allEvents.push(gameCreatedEvent);
    actualState = { player1Id: 'alice', player2Id: 'bob', phase: 'map_selection' };

    // 2. Map selection
    {
      const { after, events } = simulateTransition('map_selection_', actualState, s => {
        s.phase = 'initiative';
        s.selectedMap = 'mos-eisley-outskirts';
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 3. Initiative
    {
      const { after, events } = simulateTransition('determine_initiative_', actualState, s => {
        s.phase = 'zone_selection';
        s.initiativePlayerNum = 1;
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 4. Deployment zone
    {
      const { after, events } = simulateTransition('deployment_zone_red_', actualState, s => {
        s.phase = 'deployment';
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 5. Deploy figures
    {
      const { after, events } = simulateTransition('deploy_pick_', actualState, s => {
        s.figurePositions = { 1: { 'Trooper-0-0': 'A1', 'Trooper-0-1': 'A2' }, 2: {} };
        s.dcHealthState = { 'Trooper-0-0': 3, 'Trooper-0-1': 3 };
      });
      actualState = after;
      allEvents.push(...events);
    }
    {
      const { after, events } = simulateTransition('deploy_pick_', actualState, s => {
        s.figurePositions[2] = { 'Rebel-0-0': 'D4', 'Rebel-0-1': 'D5' };
        s.dcHealthState['Rebel-0-0'] = 5;
        s.dcHealthState['Rebel-0-1'] = 5;
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 6. Deployment completed
    {
      const { after, events } = simulateTransition('deployment_done_', actualState, s => {
        s.player1Deployed = true;
      });
      actualState = after;
      allEvents.push(...events);
    }
    {
      const { after, events } = simulateTransition('deployment_done_', actualState, s => {
        s.player2Deployed = true;
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 7. Round 1 start
    {
      const { after, events } = simulateTransition('end_start_of_round_', actualState, s => {
        s.currentRound = 1;
        s.roundPhase = 'start_of_round';
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 8. Activation phase
    {
      const { after, events } = simulateTransition('status_phase_', actualState, s => {
        s.roundPhase = 'activation';
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 9. Activate DC
    {
      const { after, events } = simulateTransition('dc_activate_', actualState, s => {
        s.dcActionsData = { 'msg-trooper': { remaining: 2, total: 2, threadId: null, messageId: null, specialsUsed: [], selectedFigure: null } };
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 10. Move figure
    {
      const { after, events } = simulateTransition('move_pick_', actualState, s => {
        s.figurePositions[1]['Trooper-0-0'] = 'B1';
        s.moveInProgress = { 'Trooper-0-0': { remaining: 3 } };
      });
      actualState = after;
      allEvents.push(...events);
    }
    {
      const { after, events } = simulateTransition('move_pick_', actualState, s => {
        s.figurePositions[1]['Trooper-0-0'] = 'C1';
        s.moveInProgress = { 'Trooper-0-0': { remaining: 2 } };
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 11. Apply condition
    {
      const { after, events } = simulateTransition('cc_play_', actualState, s => {
        s.figureConditions = { 'Trooper-0-0': ['Focus'] };
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 12. Gain power token
    {
      const { after, events } = simulateTransition('cc_play_', actualState, s => {
        s.figurePowerTokens = { 'Trooper-0-0': ['Hit'] };
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 13. Take damage
    {
      const { after, events } = simulateTransition('combat_resolve_ready_', actualState, s => {
        s.dcHealthState['Rebel-0-0'] = 2; // took 3 damage
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 14. End activation
    {
      const { after, events } = simulateTransition('end_turn_', actualState, s => {
        s.dcActionsData['msg-trooper'].remaining = 0;
        delete s.moveInProgress;
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 15. End of round
    {
      const { after, events } = simulateTransition('end_end_of_round_', actualState, s => {
        s.roundPhase = 'end_of_round';
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 16. Round ended
    {
      const { after, events } = simulateTransition('end_end_of_round_', actualState, s => {
        s.roundPhase = null;
      });
      actualState = after;
      allEvents.push(...events);
    }

    // 17. Round 2 start
    {
      const { after, events } = simulateTransition('end_start_of_round_', actualState, s => {
        s.currentRound = 2;
        s.roundPhase = 'start_of_round';
      });
      actualState = after;
      allEvents.push(...events);
    }

    // Now replay all events through the reducer
    let replayedState = {};
    for (const event of allEvents) {
      replayedState = gameReducer(replayedState, event);
    }

    // Compare on COMPARABLE_KEYS
    const mismatches = [];
    for (const key of COMPARABLE_KEYS) {
      const replayedVal = JSON.stringify(replayedState[key]);
      const actualVal = JSON.stringify(actualState[key]);
      if (replayedVal !== actualVal) {
        mismatches.push({ key, replayed: replayedState[key], actual: actualState[key] });
      }
    }

    // Report results
    console.log(`  Replay accuracy: ${COMPARABLE_KEYS.length - mismatches.length}/${COMPARABLE_KEYS.length} keys match`);
    if (mismatches.length > 0) {
      console.log('  Mismatches:');
      for (const m of mismatches) {
        console.log(`    ${m.key}: replayed=${JSON.stringify(m.replayed)?.slice(0, 80)} actual=${JSON.stringify(m.actual)?.slice(0, 80)}`);
      }
    }

    // Assert critical keys match
    assert.equal(replayedState.currentRound, actualState.currentRound, 'currentRound should match');
    assert.equal(replayedState.roundPhase, actualState.roundPhase, 'roundPhase should match');
    assert.deepEqual(replayedState.figurePositions, actualState.figurePositions, 'figurePositions should match');
    assert.deepEqual(replayedState.figureConditions, actualState.figureConditions, 'figureConditions should match');
    assert.deepEqual(replayedState.figurePowerTokens, actualState.figurePowerTokens, 'figurePowerTokens should match');

    // Note: 'phase' may differ (reducer tracks via phase transitions, test doesn't)
    // Note: 'moveInProgress' may have empty {} vs undefined (reducer initializes it)
    // Note: VP objects initialized by GameCreated reducer but not in test's actual state
    // These are expected divergences in the test simulation, not bugs in production.

    // Log total events generated
    console.log(`  Total events generated: ${allEvents.length}`);
    console.log(`  Event types: ${[...new Set(allEvents.map(e => e.type))].join(', ')}`);
  });

  it('combat lifecycle produces accurate replay', () => {
    let actualState = {
      figurePositions: { 1: { 'Trooper-0-0': 'B2' }, 2: { 'Rebel-0-0': 'C3' } },
      dcHealthState: { 'Trooper-0-0': 5, 'Rebel-0-0': 4 },
      currentRound: 1,
      roundPhase: 'activation',
    };
    let allEvents = [];

    // Declare combat
    {
      const { after, events } = simulateTransition('attack_target_', actualState, s => {
        s.pendingCombat = {
          attackerMsgId: 'msg-t', defenderMsgId: 'msg-r',
          attackerPlayerNum: 1, defenderPlayerNum: 2,
          p1Ready: false, p2Ready: false,
        };
      });
      actualState = after;
      allEvents.push(...events);
    }

    // Both ready
    {
      const { after, events } = simulateTransition('combat_ready_', actualState, s => {
        s.pendingCombat.p1Ready = true;
      });
      actualState = after;
      allEvents.push(...events);
    }
    {
      const { after, events } = simulateTransition('combat_ready_', actualState, s => {
        s.pendingCombat.p2Ready = true;
      });
      actualState = after;
      allEvents.push(...events);
    }

    // Roll dice
    {
      const { after, events } = simulateTransition('combat_roll_', actualState, s => {
        s.pendingCombat.attackRoll = [{ color: 'green', face: { dmg: 2, surge: 1, acc: 3 } }];
      });
      actualState = after;
      allEvents.push(...events);
    }
    {
      const { after, events } = simulateTransition('combat_roll_', actualState, s => {
        s.pendingCombat.defenseRoll = [{ color: 'black', face: { block: 1, evade: 0 } }];
      });
      actualState = after;
      allEvents.push(...events);
    }

    // Resolve combat
    {
      const { after, events } = simulateTransition('combat_resolve_ready_', actualState, s => {
        delete s.pendingCombat;
        s.dcHealthState['Rebel-0-0'] = 3; // 1 damage dealt
      });
      actualState = after;
      allEvents.push(...events);
    }

    // Replay
    let replayedState = {
      figurePositions: { 1: { 'Trooper-0-0': 'B2' }, 2: { 'Rebel-0-0': 'C3' } },
      dcHealthState: { 'Trooper-0-0': 5, 'Rebel-0-0': 4 },
      currentRound: 1,
      roundPhase: 'activation',
    };
    for (const event of allEvents) {
      replayedState = gameReducer(replayedState, event);
    }

    // pendingCombat should be cleared
    assert.equal(replayedState.pendingCombat, undefined, 'pendingCombat should be cleared after resolve');
    // Health should reflect damage
    assert.equal(replayedState.dcHealthState['Rebel-0-0'], 3, 'Rebel health should be 3 after 1 damage');

    console.log(`  Combat events: ${allEvents.map(e => e.type).join(' → ')}`);
  });

  it('condition + token lifecycle produces accurate replay', () => {
    let actualState = {
      figureConditions: {},
      figurePowerTokens: {},
    };
    let allEvents = [];

    // Apply multiple conditions
    {
      const { after, events } = simulateTransition('cc_play_', actualState, s => {
        s.figureConditions = { 'fig-0-0': ['Focus', 'Hidden'] };
      });
      actualState = after;
      allEvents.push(...events);
    }

    // Add tokens
    {
      const { after, events } = simulateTransition('cc_play_', actualState, s => {
        s.figurePowerTokens = { 'fig-0-0': ['Hit', 'Block'] };
      });
      actualState = after;
      allEvents.push(...events);
    }

    // Remove one condition, spend one token
    {
      const { after, events } = simulateTransition('combat_resolve_ready_', actualState, s => {
        s.figureConditions['fig-0-0'] = ['Hidden']; // Focus consumed
        s.figurePowerTokens['fig-0-0'] = ['Block']; // Hit spent
      });
      actualState = after;
      allEvents.push(...events);
    }

    // Replay
    let replayedState = { figureConditions: {}, figurePowerTokens: {} };
    for (const event of allEvents) {
      replayedState = gameReducer(replayedState, event);
    }

    assert.deepEqual(replayedState.figureConditions['fig-0-0'], ['Hidden']);
    assert.deepEqual(replayedState.figurePowerTokens['fig-0-0'], ['Block']);
  });
});
