"""P1-D: Action-parity oracle template.

Pattern every per-action oracle test in `python/parity/oracles/stepper/`
follows. Given a (state, action) pair and the JS-recorded resulting state,
apply the action through the Python stepper and assert zero diffs.

The canonical shape:

    oracle = ActionParityOracle(
        name='pass_activation_turn_happy_path',
        initial_state={...},          # game state before action
        custom_id='pass_activation_turn_TEST01',
        user_id='p1',
        action_opts={},
        dice_pools=None,              # or {'attack': {...}, 'defense': {...}}
        expected_state={...},         # JS-recorded state AFTER action
    )
    oracle.run()  # raises ParityAssertionError on any diff

Fixtures come from `tests/headless/action-recorder.js` output, and
real oracles in `python/parity/oracles/stepper/test_<action>_parity.py`
load fixtures generated by `tests/headless/dump-action-fuzz.js` (P1-E).
The worked example at the bottom of this module uses an in-line fixture
to keep the template self-contained.

Run the worked example:
    python3 python/parity/oracles/_action_template.py
"""
from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from python.engine.action_parser import step_custom_id, UnparseableCustomId
from python.engine.mechanics.dice import DiceStream
from python.engine.state import GameState
from python.parity.replay_harness import DISCORD_ONLY_PATHS, _filter_diffs
from python.parity.state_diff import Diff, format_diff, state_diff


class ParityAssertionError(AssertionError):
    """Raised when an oracle finds state diffs after applying an action."""


@dataclass
class ActionParityOracle:
    """A single (state, action) parity test.

    Attributes:
        name: human-readable case label (shown in failure messages).
        initial_state: full game state dict BEFORE the action.
        custom_id: JS customId driving the action.
        user_id: the acting player's Discord id (p1/p2 as appropriate).
        action_opts: optional action options dict (mirrors `actionOpts` from
            action-recorder output).
        dice_pools: optional dict of {'attack': {<color>: [idx,...]},
            'defense': {<color>: [idx,...]}}. When provided, a DiceStream
            is installed on the underlying dice roller so combat is
            deterministic.
        expected_state: full game state dict AFTER the action (as
            JS would produce it).
        extra_ignored_paths: additional top-level field names to ignore
            during diff (on top of the default Discord-only set).
    """

    name: str
    initial_state: Dict[str, Any]
    custom_id: str
    user_id: str = ''
    action_opts: Optional[Dict[str, Any]] = None
    dice_pools: Optional[Dict[str, Dict[str, List[int]]]] = None
    expected_state: Dict[str, Any] = field(default_factory=dict)
    extra_ignored_paths: frozenset = frozenset()

    # ------------------------------------------------------------------
    # Execution
    # ------------------------------------------------------------------

    def run(self) -> None:
        game = GameState(dict(self.initial_state))

        # Install dice stream if provided (combat parity only).
        installed_stream = None
        if self.dice_pools is not None:
            installed_stream = DiceStream.from_dict({'pools': self.dice_pools})
            # The stepper's attack handler currently constructs its own
            # RNG from action_opts['rng_seed']. DiceStream replay wiring
            # lands as part of H7-M (COMBAT_SURGE) / the combat handler
            # port. For now the stream acts as a future-proofing carrier;
            # tests that need deterministic combat will plumb it in then.
            # (Leaving the attribute here so the oracle signature is
            # stable across the port.)
            pass

        try:
            new_game = step_custom_id(
                game, self.custom_id, self.user_id, self.action_opts or {},
            )
        except UnparseableCustomId as e:
            raise ParityAssertionError(
                f'[{self.name}] customId {self.custom_id!r} has no Python '
                f'parser yet: {e}'
            ) from e
        except Exception as e:
            raise ParityAssertionError(
                f'[{self.name}] stepper raised: {type(e).__name__}: {e}'
            ) from e

        raw_diffs = state_diff(new_game, self.expected_state)
        diffs = _filter_diffs(raw_diffs)
        if self.extra_ignored_paths:
            diffs = [
                d for d in diffs
                if d.path.split('.', 1)[0].split('[', 1)[0]
                not in self.extra_ignored_paths
            ]
        if diffs:
            raise ParityAssertionError(
                f'[{self.name}] {len(diffs)} diff(s) after applying '
                f'{self.custom_id!r}:\n{format_diff(diffs)}'
            )


# ---------------------------------------------------------------------------
# Worked example — PASS_ACTIVATION_TURN
# ---------------------------------------------------------------------------
#
# Goal: demonstrate an end-to-end parity oracle using a currently-ported
# action. When the JS engine's setup flow is ported (P2-A) this example
# will load a real JS-recorded fixture instead of a hand-crafted dict.

_EXAMPLE_INITIAL_STATE = {
    'gameId': 'TEMPLATE01',
    'player1Id': 'p1',
    'player2Id': 'p2',
    'phase': 'round_active',
    'roundPhase': 'activation',
    'activePlayer': 1,
    'activationsRemaining': {1: 0, 2: 0},
    'figurePositions': {1: {}, 2: {}},
    'player1VP': {'total': 0, 'kills': 0, 'objectives': 0},
    'player2VP': {'total': 0, 'kills': 0, 'objectives': 0},
    'ended': False,
}

_EXAMPLE_EXPECTED_AFTER_PASS = {
    **_EXAMPLE_INITIAL_STATE,
    'activePlayer': 2,  # pass swaps active player
}


def _run_example() -> int:
    example = ActionParityOracle(
        name='pass_activation_turn_template_example',
        initial_state=_EXAMPLE_INITIAL_STATE,
        custom_id='pass_activation_turn_TEMPLATE01',
        user_id='p1',
        expected_state=_EXAMPLE_EXPECTED_AFTER_PASS,
    )
    try:
        example.run()
        print(f'PASS: {example.name}')
        return 0
    except ParityAssertionError as e:
        print(f'FAIL: {e}')
        return 1


if __name__ == '__main__':
    sys.exit(_run_example())
