export const PHASE_EVENTS = {
  GameCreated: 'GameCreated',
  MapSelected: 'MapSelected',
  InitiativeDetermined: 'InitiativeDetermined',
  DeploymentZoneChosen: 'DeploymentZoneChosen',
  DeploymentCompleted: 'DeploymentCompleted',
  AttachmentsConfirmed: 'AttachmentsConfirmed',
  CommandCardsDrawn: 'CommandCardsDrawn',
  RoundStarted: 'RoundStarted',
  ActivationPhaseStarted: 'ActivationPhaseStarted',
  ActivationPhaseEnded: 'ActivationPhaseEnded',
  EndOfRoundStarted: 'EndOfRoundStarted',
  RoundEnded: 'RoundEnded',
  GameEnded: 'GameEnded',
  PhaseGateOpened: 'PhaseGateOpened',
  PhaseGatePlayerReady: 'PhaseGatePlayerReady',
  PhaseGateCleared: 'PhaseGateCleared',
};

export const PHASE_EVENT_SCHEMAS = {
  GameCreated: { required: ['player1Id', 'player2Id', 'generalId'] },
  MapSelected: { required: ['mapId'] },
  InitiativeDetermined: { required: ['initiativePlayerNum'] },
  DeploymentZoneChosen: { required: ['playerNum', 'zoneId'] },
  DeploymentCompleted: { required: ['playerNum'] },
  AttachmentsConfirmed: { required: ['playerNum'] },
  CommandCardsDrawn: { required: ['playerNum', 'count'] },
  RoundStarted: { required: ['roundNumber'] },
  ActivationPhaseStarted: { required: [] },
  ActivationPhaseEnded: { required: [] },
  EndOfRoundStarted: { required: [] },
  RoundEnded: { required: ['roundNumber'] },
  GameEnded: { required: ['winnerId'] },
  PhaseGateOpened: { required: ['gateType'] },
  PhaseGatePlayerReady: { required: ['playerNum'] },
  PhaseGateCleared: { required: ['gateType'] },
};
