/**
 * Interaction router: map customId to handler key (prefix) for dispatch.
 * Single place to register all customId prefixes; order matters (first match wins).
 */

/** Button interaction prefixes, in dispatch order. */
const BUTTON_PREFIXES = [
  'request_resolve_',
  'request_reject_',
  'deck_illegal_play_',
  'deck_illegal_redo_',
  'dc_activate_',
  'dc_unactivate_',
  'dc_toggle_',
  'dc_deplete_',
  'dc_cc_special_',
  'dc_cc_eoa_',
  'dc_cc_double_',
  'dc_cc_defender_',
  'dc_ability_choice_',
  'pounce_space_',
  'rush_push_fig_',
  'rush_push_space_',
  'rush_push_skip_',
  'ee3_pick_die_',
  'dc_move_',
  'dc_attack_',
  'dc_interact_',
  'dc_special_',
  'special_done_',
  'move_mp_',
  'move_adjust_mp_',
  'move_back_letters_',
  'move_letter_',
  'move_pick_',
  'attack_target_',
  'cleave_target_',
  'combat_resolve_ready_',
  'combat_ready_',
  'combat_roll_',
  'combat_surge_',
  'combat_reroll_',
  'pre_reroll_',
  'combat_passive_',
  'combat_token_',
  'sidewinder_apply_',
  'sidewinder_skip_',
  'boltslinger_target_',
  'boltslinger_skip_',
  'indiscriminate_die_',
  'indiscriminate_skip_',
  'fighting_knife_target_',
  'fighting_knife_skip_',
  'concussive_bolt_push_',
  'concussive_bolt_skip_',
  'spread_pain_cond_',
  'spread_pain_fig_',
  'spread_pain_skip_',
  'missile_salvo_die_',
  'missile_salvo_done_',
  'bleed_accept_',
  'bleed_prevent_',
  'reaction_use_',
  'reaction_skip_',
  'mastery_pick_',
  'mastery_skip_',
  'interrogate_pick_',
  'interrogate_discard_',
  'interrogate_skip_',
  'still_faster_use_',
  'still_faster_skip_',
  'still_faster_dc_pick_',
  'squad_swarm_yes_',
  'squad_swarm_no_',
  'overdrive_use_',
  'self_destruct_protocol_use_',
  'self_destruct_protocol_skip_',
  'last_resort_use_',
  'last_resort_skip_',
  'on_diplomatic_',
  'scavenged_walker_attack_',
  'scavenged_walker_skip_',
  'overwatch_space_',
  'ob_deplete_',
  'ob_skip_',
  'ob_space_',
  'self_destruct_probe_use_',
  'self_destruct_probe_skip_',
  'tough_luck_remove_',
  'tough_luck_skip_',
  'bel_reorder_1_',
  'bel_reorder_2_',
  'there_is_no_try_die_',
  'there_is_no_try_face_',
  'there_is_no_try_skip_',
  'vet_instincts_pick_',
  'hunter_protocol_trigger_',
  'hunter_protocol_skip_',
  'right_back_block_',
  'right_back_nodmg_',
  'figurehead_use_',
  'figurehead_skip_',
  'lasat_die_',
  'lasat_face_',
  'false_orders_action_',
  'false_orders_space_',
  'false_orders_atk_',
  'devaron_door_open_',
  'devaron_crate_push_',
  'krykna_push_',
  'act_passive_',
  'status_phase_',
  'dc_end_activation_',
  'end_end_of_round_',
  'end_start_of_round_',
  'map_selection_',
  'draft_random_',
  'pass_activation_turn_',
  'end_turn_',
  'confirm_activate_',
  'cancel_activate_',
  'interact_cancel_',
  'interact_choice_',
  'refresh_map_',
  'refresh_all_',
  'undo_',
  'determine_initiative_',
  'deployment_zone_red_',
  'deployment_zone_blue_',
  'deployment_fig_',
  'deployment_orient_',
  'deploy_pick_',
  'loadout_pick_',
  'form_pick_',
  'deployment_done_',
  'cc_shuffle_draw_',
  'cc_confirm_play_',
  'cc_cancel_play_',
  'cc_play_',
  'cc_draw_',
  'cc_search_discard_',
  'cc_close_discard_',
  'cc_discard_',
  'cc_choice_',
  'cc_space_',
  'illegal_cc_ignore_',
  'illegal_cc_unplay_',
  'negation_play_',
  'negation_let_resolve_',
  'celebration_play_',
  'celebration_pass_',
  'botmenu_archive_yes_',
  'botmenu_archive_no_',
  'botmenu_kill_yes_',
  'botmenu_kill_no_',
  'botmenu_archive_',
  'botmenu_kill_',
  'kill_game_',
  'default_deck_',
  'squad_select_',
  'fast_forward_',
  'lobby_join_',
  'lobby_start_',
  'create_game',
  'join_game',
];

/** Modal submit prefixes. */
const MODAL_PREFIXES = [
  'squad_modal_',
  'deploy_modal_',
  'devaron_crate_modal_',
  'krykna_push_modal_',
];

/** String select menu prefixes. */
const SELECT_PREFIXES = [
  'dc_fig_select_',
  'arsenal_pick_',
  'setup_attach_to_',
  'map_selection_draw_',
  'map_selection_pick_',
  'map_selection_menu_',
  'cc_attach_to_',
  'cc_play_select_',
  'cc_discard_select_',
];

/**
 * Return the first matching handler key (prefix) for the given customId and interaction type.
 * @param {string} customId
 * @param {'button'|'modal'|'select'} type
 * @returns {string|null}
 */
export function getHandlerKey(customId, type) {
  if (!customId || typeof customId !== 'string') return null;
  const list = type === 'button' ? BUTTON_PREFIXES : type === 'modal' ? MODAL_PREFIXES : SELECT_PREFIXES;
  for (const prefix of list) {
    if (customId.startsWith(prefix)) return prefix;
  }
  return null;
}

export { BUTTON_PREFIXES, MODAL_PREFIXES, SELECT_PREFIXES };
